#!/bin/bash

# This is what runs in the actual Gradescope container. You shouldn't need it in development.

## Run a server with the student submission

cd /autograder/submission

# remove macos garbage >:(
find . -type f -name '.DS_Store' -delete
find . -type d -name '__MACOSX' -exec rm -r {} \+

# if the only thing in the submission is a top-level directory, enter it
if [ "$(ls -A | wc -l)" = 1 ] && [ -d "$(ls -A)" ]; then
  cd */
fi

SUBMISSION_DIR=$(pwd)

python3 -m http.server 6160 &> /dev/null &

## Run the tests

cd /autograder/playwright && npx playwright test

## Upload the Playwright report and write the resulting URL to a file

cd /autograder && bash upload-report.sh > /autograder/report-data.json
cat /autograder/report-data.json # seems handy
cd /autograder && bash upload-submission.sh $SUBMISSION_DIR > /autograder/submission-data.json

## Figure out how many points to award and tell Gradescope

cd /autograder/process-results && node process-results.js
cp /autograder/process-results/results.json /autograder/results/results.json
